name: Code Coverage

on:
  - pull_request

env:
  THRESHOLD-TOTAL: 55

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Test coverage
        run: |
          go test -v ./... -coverprofile=./cover.out
          go tool cover -html=cover.out -o coverage.html

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html

      - name: Check Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          threshold-total: ${{env.THRESHOLD-TOTAL}}